services:
  currency:
    build: currency
    environment:
      - REDIS_URL=redis://${REDIS_USER}:${REDIS_PASSWORD}@localhost:6379/0
    depends_on:
      - "redis"
  redis:
    image: "redis:7.4-rc2-alpine3.20"
    ports:
      - "6379:6379"
    environment:
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
